rootProject.name = 'datamask'

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}

new File('.').eachFileRecurse {
    if (it.name == "build.gradle" && it.parentFile.name != '.' && it.parentFile.name != 'buildSrc') {
        println "Included directory ${it.parentFile.name} due to ${it}"
        include it.parentFile.name
    }
}
