package ch.raph.datamask.processor.plan;

import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Turns a {@link PlanModel} into the source of one {@code GeneratedMaskPlan}.
 *
 * <p>Everything is written fully qualified and nothing is imported. Generated code lands in the
 * application's own package, where a short name could collide with something already there, and a
 * name that resolves differently depending on what else is in scope is not a debate worth having in
 * code nobody reads.
 *
 * <p>What must not appear in the output: {@code java.lang.reflect}, {@code MethodHandle},
 * {@code Class.forName}, {@code setAccessible}. {@code GeneratedSourceTest} asserts exactly that,
 * because avoiding them is the whole reason this module exists.
 */
final class PlanWriter {

    /** The casts come out of an {@code Object[]}, so a primitive member needs its box named. */
    private static final Map<String, String> BOXES = Map.of(
            "boolean", "java.lang.Boolean",
            "byte", "java.lang.Byte",
            "char", "java.lang.Character",
            "short", "java.lang.Short",
            "int", "java.lang.Integer",
            "long", "java.lang.Long",
            "float", "java.lang.Float",
            "double", "java.lang.Double");

    private PlanWriter() {}

    static String write(PlanModel model) {
        StringBuilder out = new StringBuilder(2048);
        if (!model.packageName().isEmpty()) {
            out.append("package ").append(model.packageName()).append(";\n\n");
        }
        out.append("""
                /**
                 * The masking plan for {@link %s}, worked out while it was compiled.
                 *
                 * <p>Generated by datamask-build-processor. Do not edit: it is rewritten on every build,
                 * and nothing loads it except GeneratedMaskPlanCompiler, through META-INF/services.
                 */
                public final class %s implements %s {

                    @Override
                    public java.lang.Class<?> type() {
                        return %s.class;
                    }

                    @Override
                    @SuppressWarnings({"unchecked", "rawtypes"})
                    public %s plan() {
                        java.util.List<%s> members = java.util.List.of(
                %s);

                        return new %s(
                                %s.class,
                                members,
                                (original, values) -> %s);
                    }
                %s}
                """.formatted(
                        model.targetName(),
                        model.generatedSimpleName(),
                        Names.GENERATED_MASK_PLAN,
                        model.targetName(),
                        Names.MASK_PLAN,
                        Names.MEMBER_PLAN,
                        members(model),
                        Names.MASK_PLAN,
                        model.targetName(),
                        rebuildExpression(model),
                        rebuildHelper(model).orElse("")));
        return out.toString();
    }

    /**
     * Indentation is written out rather than left to the text blocks below.
     *
     * <p>A text block strips its own incidental indentation, so a nested fragment substituted into
     * one arrives flattened against the left margin. Generated code is read exactly when something
     * has gone wrong with a mask, and a wall of unindented calls is the worst possible moment to
     * meet one.
     */
    private static final String MEMBER = " ".repeat(16);

    private static final String ARGUMENT = " ".repeat(24);
    private static final String ATTRIBUTE = " ".repeat(32);

    private static String members(PlanModel model) {
        return model.members().stream()
                .map(PlanWriter::member)
                .reduce((a, b) -> a + ",\n" + b)
                .orElse("");
    }

    private static String member(PlanModel.Member member) {
        return MEMBER + "new " + Names.MEMBER_PLAN + "(\n"
                + ARGUMENT + quoted(member.name()) + ",\n"
                + ARGUMENT + member.declaredType() + ".class,\n"
                + ARGUMENT + "target -> " + member.readExpression() + ",\n"
                + ARGUMENT + action(member.action()) + ")";
    }

    private static String action(PlanModel.Action action) {
        return switch (action) {
            case PlanModel.Action.Keep ignored -> Names.MASK_ACTION + ".KEEP";
            case PlanModel.Action.Descend ignored -> Names.MASK_ACTION + ".DESCEND";
            case PlanModel.Action.Mask mask ->
                "new " + Names.MASK_ACTION + ".Mask(" + descriptor(mask.descriptor()) + ")";
        };
    }

    /**
     * The real constructor, with its arguments in order — never a pre-resolved descriptor.
     *
     * <p>{@code PiiDescriptor}'s compact constructor forces {@code keep = 0} for a category that is
     * never partially revealed, and that correction has to happen here as well. Emitting resolved
     * fields instead would let a generated plan hold a card verification value with a {@code keep}
     * the runtime would have refused: the mask would be weaker in generated code than in reflected
     * code, which is the one difference between the two that would actually matter.
     */
    private static String descriptor(PlanModel.Descriptor descriptor) {
        return "new " + Names.PII_DESCRIPTOR + "(\n"
                + ATTRIBUTE + descriptor.category() + ",\n"
                + ATTRIBUTE + descriptor.sensitivity() + ",\n"
                + ATTRIBUTE + descriptor.strategy() + ",\n"
                + ATTRIBUTE + descriptor.keep() + ",\n"
                + ATTRIBUTE + charLiteral(descriptor.padding()) + ",\n"
                + ATTRIBUTE + quoted(descriptor.replacement()) + ",\n"
                + ATTRIBUTE + descriptor.maskerType() + ".class,\n"
                + ATTRIBUTE + quoted(descriptor.purpose()) + ")";
    }

    private static String rebuildExpression(PlanModel model) {
        if (model.rebuild() instanceof PlanModel.Rebuild.Constructor constructor) {
            List<String> parameters = constructor.parameterTypes();
            StringBuilder arguments = new StringBuilder();
            for (int i = 0; i < parameters.size(); i++) {
                arguments.append(i == 0 ? "\n" : ",\n").append(ARGUMENT).append(cast(parameters.get(i), i));
            }
            return "new " + model.targetName() + "(" + arguments + ")";
        }
        // A lambda body cannot hold statements and stay an expression, so the writes go into a
        // helper the generated class declares for itself.
        return "rebuild(values)";
    }

    private static Optional<String> rebuildHelper(PlanModel model) {
        if (!(model.rebuild() instanceof PlanModel.Rebuild.NoArgumentsThenWrite noArguments)) {
            return Optional.empty();
        }
        StringBuilder writes = new StringBuilder();
        List<PlanModel.Write> members = noArguments.writes();
        for (int i = 0; i < members.size(); i++) {
            PlanModel.Write write = members.get(i);
            writes.append("        copy.").append(write.name());
            writes.append(
                    write.setter()
                            ? "(" + cast(write.declaredType(), i) + ");\n"
                            : " = " + cast(write.declaredType(), i) + ";\n");
        }
        return Optional.of("""

                    @SuppressWarnings({"unchecked", "rawtypes"})
                    private static %s rebuild(java.lang.Object[] values) {
                        %s copy = new %s();
                %s        return copy;
                    }
                """.formatted(model.targetName(), model.targetName(), model.targetName(), writes));
    }

    /**
     * {@code (java.lang.Integer) values[3]} rather than {@code (int) values[3]}: naming the
     * reference type makes a wrong value a {@code ClassCastException} that names both types, instead
     * of an unboxing {@code NullPointerException} that names neither.
     */
    private static String cast(String declaredType, int index) {
        return "(" + BOXES.getOrDefault(declaredType, declaredType) + ") values[" + index + "]";
    }

    private static String quoted(String value) {
        StringBuilder out = new StringBuilder(value.length() + 2).append('"');
        for (int i = 0; i < value.length(); i++) {
            out.append(escape(value.charAt(i), '"'));
        }
        return out.append('"').toString();
    }

    private static String charLiteral(char value) {
        return "'" + escape(value, '\'') + "'";
    }

    private static String escape(char value, char quote) {
        if (value == quote) {
            return "\\" + quote;
        }
        return switch (value) {
            case '\\' -> "\\\\";
            case '\n' -> "\\n";
            case '\r' -> "\\r";
            case '\t' -> "\\t";
            case '\b' -> "\\b";
            case '\f' -> "\\f";
            // Anything outside printable ASCII goes out as an escape: the file is written with
            // whatever encoding the compiler was given, and a literal é does not survive all of them.
            default -> value >= 0x20 && value < 0x7F ? String.valueOf(value) : String.format("\\u%04x", (int) value);
        };
    }
}
